title: Michael R Walton
url: "https://www.michaelrwalton.com"
baseurl: ""
include: ["_pages"]
description: "Boston based Software Engineer"
author: Michael Walton

markdown: kramdown

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "LinkedIn"
   link: "https://www.linkedin.com/in/michaelrwalton"
 - name: "GitHub"
   link: "https://github.com/michaelrwalton"

