title: Michael R Walton
url: "https://www.michaelrwalton.com"
baseurl: ""
include: ["_pages"]

markdown: kramdown

sass:
    style: compressed
    sass_dir: _sass

# nav:
#  - name: "Resume"
#    link: "resume.pdf"
